### ISSUE TITLE
[FEATURE] Patch 5.5 Compatibility 

### ISSUE THREAD

**Issue by zeparu** [fosspill/FFXIV_Modding_Tool#242]
new patch new me

current output, trying to backup index files
```
 ~  ffmt b
Validating cache...
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (Non-negative number required. (Parameter 'count')) (Non-negative number required. (Parameter 'count')))
 ---> System.AggregateException: One or more errors occurred. (Non-negative number required. (Parameter 'count')) (Non-negative number required. (Parameter 'count'))
 ---> System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at xivModdingFramework.Items.Categories.Gear.<>c__DisplayClass6_0.<GetUnCachedGearList>b__1(KeyValuePair`2 item)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at xivModdingFramework.Items.Categories.Gear.<>c__DisplayClass6_0.<GetUnCachedGearList>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at xivModdingFramework.Items.Categories.Gear.GetUnCachedGearList()
   at xivModdingFramework.Cache.XivCache.RebuildGearCache()
   at xivModdingFramework.Cache.XivCache.RebuildItemsCache()
   at xivModdingFramework.Cache.XivCache.<>c__DisplayClass30_0.<<RebuildCache>b__0>d.MoveNext()
 ---> (Inner Exception #1) System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at xivModdingFramework.Items.Categories.Gear.<>c__DisplayClass6_0.<GetUnCachedGearList>b__1(KeyValuePair`2 item)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at xivModdingFramework.Cache.XivCache.RebuildCache(CacheRebuildReason reason)
   at xivModdingFramework.Cache.XivCache.SetGameInfo(GameInfo gameInfo, Boolean enableCacheWorker)
   at xivModdingFramework.Cache.XivCache.SetGameInfo(DirectoryInfo gameDirectory, XivLanguage language, Int32 dxMode, Boolean validateCache, Boolean enableCacheWorker)
   at FFXIV_Modding_Tool.Commandline.Arguments.CheckGameDirectory()
   at FFXIV_Modding_Tool.Commandline.Arguments.ActionRequirementsChecker(String requestedAction)
   at FFXIV_Modding_Tool.Commandline.Arguments.ReadArguments(String[] args)
   at FFXIV_Modding_Tool.Commandline.Arguments.ArgumentHandler(String[] args)
   at FFXIV_Modding_Tool.MainClass.Main(String[] args)
/usr/bin/ffmt: line 3: 38142 Aborted                 (core dumped) $INSTALL_DIR/ffmt "$@"

```

**Comment by lillelilje** [comment]
Indeed!

A new release is already lined up as a draft here. I'd estimate an hour until it's ready

**Comment by lillelilje** [comment]
https://github.com/fosspill/FFXIV_Modding_Tool/releases/tag/v0.9.9
